// Typed command set (T06, T-REQ-005), generated from .bb-authority/contracts/command-contract.json
// at write time. `dispatch_rule`: no UI handler mutates semantic state directly — every
// semantic change dispatches exactly one command to reduceCommand(state, command).

export const CommandType = Object.freeze({
  BOOTSTRAP_READY: 'BOOTSTRAP_READY',
  BOOTSTRAP_FAILED: 'BOOTSTRAP_FAILED',
  ENTER_WORK: 'ENTER_WORK',
  INTERRUPT_ONBOARDING_WITH_OBJECT: 'INTERRUPT_ONBOARDING_WITH_OBJECT',
  RETURN_TO_WHOLE_FIELD: 'RETURN_TO_WHOLE_FIELD',
  PREVIEW_OBJECT: 'PREVIEW_OBJECT',
  CLEAR_PREVIEW: 'CLEAR_PREVIEW',
  COMMIT_OBJECT: 'COMMIT_OBJECT',
  INSPECT_PROJECTED_EDGE: 'INSPECT_PROJECTED_EDGE',
  CLEAR_INSPECTION: 'CLEAR_INSPECTION',
  SET_SURFACE: 'SET_SURFACE',
  SET_TYPE_VISIBILITY: 'SET_TYPE_VISIBILITY',
  SET_OBJECT_VISIBILITY: 'SET_OBJECT_VISIBILITY',
  SET_VIEW_OPTION: 'SET_VIEW_OPTION',
  ENTER_SOLO: 'ENTER_SOLO',
  EXIT_SOLO: 'EXIT_SOLO',
  RESTORE_FIELD: 'RESTORE_FIELD',
  REPLAY_ROUTE_EVENT: 'REPLAY_ROUTE_EVENT',
  CLEAR_ROUTE: 'CLEAR_ROUTE',
  CLEAR_TRACE: 'CLEAR_TRACE',
  OPEN_OVERLAY: 'OPEN_OVERLAY',
  CLOSE_OVERLAY: 'CLOSE_OVERLAY',
  REPLACE_OVERLAY: 'REPLACE_OVERLAY',
  SET_ROVING_FOCUS: 'SET_ROVING_FOCUS',
  RECONCILE_ENVIRONMENT: 'RECONCILE_ENVIRONMENT',
  RECONCILE_DOCUMENT_VISIBILITY: 'RECONCILE_DOCUMENT_VISIBILITY',
  EXTERNAL_NAVIGATION_FAILED: 'EXTERNAL_NAVIGATION_FAILED',
});

// route_policy/trace_policy per command, exactly as declared by the command contract.
export const COMMAND_SPECS = Object.freeze({
  BOOTSTRAP_READY: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'system' },
  BOOTSTRAP_FAILED: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'system' },
  ENTER_WORK: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  INTERRUPT_ONBOARDING_WITH_OBJECT: { requiredFields: ["id","source"], routePolicy: 'append-on-id-change', tracePolicy: 'record-on-id-change', origin: 'reader' },
  RETURN_TO_WHOLE_FIELD: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  PREVIEW_OBJECT: { requiredFields: ["id"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  CLEAR_PREVIEW: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  COMMIT_OBJECT: { requiredFields: ["id","source"], routePolicy: 'append-on-id-change', tracePolicy: 'record-on-id-change', origin: 'reader' },
  INSPECT_PROJECTED_EDGE: { requiredFields: ["sourceId","targetId","relOIds"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  CLEAR_INSPECTION: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  SET_SURFACE: { requiredFields: ["surface"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  SET_TYPE_VISIBILITY: { requiredFields: ["objectType","visible"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  SET_OBJECT_VISIBILITY: { requiredFields: ["id","visible"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  SET_VIEW_OPTION: { requiredFields: ["option","value"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  ENTER_SOLO: { requiredFields: ["id"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  EXIT_SOLO: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  RESTORE_FIELD: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  REPLAY_ROUTE_EVENT: { requiredFields: ["sequence"], routePolicy: 'replay', tracePolicy: 'none', origin: 'reader' },
  CLEAR_ROUTE: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  CLEAR_TRACE: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  OPEN_OVERLAY: { requiredFields: ["kind","invoker"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  CLOSE_OVERLAY: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  REPLACE_OVERLAY: { requiredFields: ["kind","invoker"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  SET_ROVING_FOCUS: { requiredFields: ["id"], routePolicy: 'none', tracePolicy: 'none', origin: 'reader' },
  RECONCILE_ENVIRONMENT: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'system' },
  RECONCILE_DOCUMENT_VISIBILITY: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'system' },
  EXTERNAL_NAVIGATION_FAILED: { requiredFields: [], routePolicy: 'none', tracePolicy: 'none', origin: 'system' },
});
